from fastapi import APIRouter, Depends, HTTPException, Security, status
from fastapi.security import APIKeyHeader

from config.settings import Settings, get_settings
from controllers.firestore_controller import get_firestore_repository
from models.requests.llm import LLMDocumentRequest
from models.responses.llm import LLMDocumentResponse
from repository.firestore_repository import FirestoreRepository
from services.llm.ingest_service import LLMService

router = APIRouter(prefix="/llm", tags=["LLM Integration"])

api_key_header = APIKeyHeader(name="X-LLM-API-Key", auto_error=True)


def verify_api_key(
    api_key: str = Security(api_key_header),
    settings: Settings = Depends(get_settings),
) -> str:
    """Validate the provided API key against the configured secret."""
    
    if api_key != settings.llm_api_key:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Invalid API Key",
        )
    return api_key


def get_llm_service(
    repository: FirestoreRepository = Depends(get_firestore_repository),
) -> LLMService:
    return LLMService(repository)


@router.post(
    "/ingest/srt",
    status_code=status.HTTP_201_CREATED,
    response_model=LLMDocumentResponse,
    summary="Ingest LLM-generated SRT content",
    response_description="Confirmation of the stored document.",
)
async def ingest_srt_content(
    request: LLMDocumentRequest,
    service: LLMService = Depends(get_llm_service),
    _auth: str = Depends(verify_api_key),
) -> LLMDocumentResponse:
    """
    Secure endpoint for storing SRT content generated by the LLM.
    
    Requires a valid 'X-LLM-API-Key' header matching the backend configuration.
    """
    
    document_id, timestamp = await service.save_srt_document(request)
    
    return LLMDocumentResponse(
        document_id=document_id,
        collection="srtDocs",
        timestamp=timestamp,
    )

